interface BOOKIF {
  maintitle: string;
  subTitle: string;
  logo: string;
  image: string;
  link: string;
  featured: boolean;
}

export const books: BOOKIF[] = [
  {
    maintitle: "فصل الشهيد اباهور",
    subTitle: "مدرسة الشمامسة",
    logo: "/image/logos/shamasa.png",
    image: "/image/books/abahoor.png",
    link: "#",
    featured: true,
  },
  {
    maintitle: "فصل الشهيد ابانوب",
    subTitle: "مدرسة الشمامسة",
    logo: "/image/logos/shamasa.png",
    image: "/image/books/abanob.png",
    link: "#",
    featured: true,
  },
  {
    maintitle: "فصل الشهيد فيلوباتير ابو سيفين",
    subTitle: "مدرسة الشمامسة",
    logo: "/image/logos/shamasa.png",
    image: "/image/books/abosefien.png",
    link: "#",
    featured: true,
  },
  {
    maintitle: "فصل الانبا انطونيوس",
    subTitle: "مدرسة الشمامسة",
    logo: "/image/logos/shamasa.png",
    image: "/image/books/antonios.png",
    link: "#",
    featured: false,
  },
  {
    maintitle: "فصل الانبا بولا",
    subTitle: "مدرسة الشمامسة",
    logo: "/image/logos/shamasa.png",
    image: "/image/books/bola.png",
    link: "#",
    featured: false,
  },
  {
    maintitle: "فصل الانبا ميخائيل",
    subTitle: "مدرسة الشمامسة",
    logo: "/image/logos/shamasa.png",
    image: "/image/books/mekhail.png",
    link: "#",
    featured: false,
  },
  {
    maintitle: "فصل الانبا موسى",
    subTitle: "مدرسة الشمامسة",
    logo: "/image/logos/shamasa.png",
    image: "/image/books/mosa.png",
    link: "#",
    featured: false,
  },
  {
    maintitle: "فصل الشهيد فيلوثيؤس",
    subTitle: "مدرسة الشمامسة",
    logo: "/image/logos/shamasa.png",
    image: "/image/books/felotheos.png",
    link: "#",
    featured: false,
  },
  {
    maintitle: "فصل الشهيد كرياكوس",
    subTitle: "مدرسة الشمامسة",
    logo: "/image/logos/shamasa.png",
    image: "/image/books/keriakos.png",
    link: "#",
    featured: false,
  },
  {
    maintitle: "فصل الشهيد مارجرجس",
    subTitle: "مدرسة الشمامسة",
    logo: "/image/logos/shamasa.png",
    image: "/image/books/gerges.png",
    link: "#",
    featured: false,
  },
  {
    maintitle: "فصل المريمات 1",
    subTitle: "مدرسة الشمامسة",
    logo: "/image/logos/shamasa.png",
    image: "/image/books/mariams1.png",
    link: "#",
    featured: false,
  },
  {
    maintitle: "فصل المريمات 2",
    subTitle: "مدرسة الشمامسة",
    logo: "/image/logos/shamasa.png",
    image: "/image/books/mariams2.png",
    link: "#",
    featured: false,
  },
  {
    maintitle: "فصل المريمات كوجي",
    subTitle: "مدرسة الشمامسة",
    logo: "/image/logos/shamasa.png",
    image: "/image/books/kogi.png",
    link: "#",
    featured: false,
  },
  {
    maintitle: "فصل الشهيد مارمينا",
    subTitle: "مدرسة الشمامسة",
    logo: "/image/logos/shamasa.png",
    image: "/image/books/mina.png",
    link: "#",
    featured: false,
  },
  {
    maintitle: "فصل رئيس الملائكة ميخائيل",
    subTitle: "مدرسة الشمامسة",
    logo: "/image/logos/shamasa.png",
    image: "/image/books/mikail.png",
    link: "#",
    featured: false,
  },
  {
    maintitle: "فصل خورس ني انجيلوس",
    subTitle: "مدرسة الشمامسة",
    logo: "/image/logos/shamasa.png",
    image: "/image/books/angelos.png",
    link: "#",
    featured: false,
  },
  {
    maintitle: "فصل خورس ني سيرافيم",
    subTitle: "مدرسة الشمامسة",
    logo: "/image/logos/shamasa.png",
    image: "/image/books/seraphem.png",
    link: "#",
    featured: false,
  },
  {
    maintitle: "فصل خورس ني شيروبيم",
    subTitle: "مدرسة الشمامسة",
    logo: "/image/logos/shamasa.png",
    image: "/image/books/sherobim.png",
    link: "#",
    featured: false,
  },
];
